apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: snapstash
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
          # envFrom:
          #   - secretRef:
          #       name: db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: db-pod-data
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: db-init
              subPath: init.sql
              readOnly: true
      volumes:
        - name: db-pod-data
          persistentVolumeClaim:
            claimName: db-data
        - name: db-init
          configMap:
            name: db-init
            defaultMode: 0444
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi