# to copy into /etc/nginx/sites-available/
server {
    listen 80;                     # écoute sur le port public 80
    server_name localhost;         # à quel nom d'hôte ce bloc répond

    location / {                   # pour TOUTES les URLs
        proxy_pass http://127.0.0.1:8000;   # → transmets à Gunicorn
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
